<!-- pg_footer.inc begin -->
       </td>
      </tr></tbody></table>
     </font></center>
    </div>
   </td>
  </tr><tr>
  <td colSpan=5 height=20 width="805" background="llblue.jpg" style="background-repeat: repeat-y;">
   <p align=center><font face="Verdana" size="1"><a href="http://ham.v4.si/">
    Avtor</a> S54MTB | Marko Pavlin | <a href="https://github.com/s54mtb">GitHub</a> 
    | <a href="https://www.qrz.com/db/S54MTB">QRZ.com</a></font></p>
  </td>
 </tr></tbody></table>
</div></body>
</html>
<!-- pg_footer.inc end -->